### ISSUE TITLE
why so stupid mistake?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/NeuralSpeech#1]
```
LightSpeech/utils/pwg_decode_from_mel.py", line 19, in load_pwg_model
    with open(config_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wavegan_pretrained/config.yaml'
```

**Comment by jinfagang** [comment]
@renqianluo  I don't know did u guys seriously tested with DOCs or codes before opensource, here is your readme claims:

![image](https://user-images.githubusercontent.com/21303438/159681810-ceafe08e-b9a8-4a7f-983e-8742033eb3b6.png)

Your config is `config.yml` and in code is `config.yaml`.

this is not a big deal though, but for a gaint company's opensource code, I suggested it would be better if make it more serious and carefully.....

**Comment by renqianluo** [comment]
Thanks for pointing this out ! This is a typo and we have fixed it.
