### ISSUE TITLE
cannot download the Trained Checkpoint.

### ISSUE THREAD

**Issue by Senpai93** [microsoft/NeuralSpeech#106]
https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech. 
Hey, 
  The url is not working anymore https://msramllasc.blob.core.windows.net/modelrelease/LightSpeech/model_ckpt_steps_100000.ckpt 
Do any one have the checkpoint. please share.

**Comment by renqianluo** [comment]
The link is fixed now. You can try again.
