### ISSUE TITLE
VideoDubber: The fairseq code for task and model architecture is not present in the folder and the folder seems to be empty.

### ISSUE THREAD

**Issue by shivamm7** [microsoft/NeuralSpeech#108]
In the VideoDubber project the fairseq folder seems to be empty. The code for the `translation_speech_length` task and the `transformer_speech_length` model architecture is not present in the folder. Is there any way to access these code files?

**Comment by wyh2000** [comment]
Hi, sorry for missing these files. Now you can find related files in fairseq folder. (Following https://github.com/microsoft/NeuralSpeech/blob/master/VideoDubber/fairseq/models/transformer_speech_length.py)
