### ISSUE TITLE
fastcorrect2 pre-trained model

### ISSUE THREAD

**Issue by nieallen** [microsoft/NeuralSpeech#11]
Could you please upload the pre-trained model  at your convenience?

**Comment by YichongLeng** [comment]
The sentencepiece model and its corresponding dictionary mentioned in FastCorrect 2 is indeed used for ASR serving of Microsoft Azure. So we cannot release it due to the company policy. I think you can pretrain the FastCorrect 2 model by your own since unpair text data is easy to find.

**Comment by nieallen** [comment]
thanks, I was trying to run data-gen.sh, the reported error is as follows:

/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 10: $'\nData pre-processing: build vocabularies and binarize training data.\n': command not found
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 12: import: command not found
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 13: import: command not found
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 14: import: command not found
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 15: import: command not found
from: can't read /var/mail/collections
from: can't read /var/mail/itertools
from: can't read /var/mail/multiprocessing
from: can't read /var/mail/fairseq
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 22: import: command not found
from: can't read /var/mail/binarizer_fc
from: can't read /var/mail/fairseq.data
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 27: syntax error near unexpected token `newline'
/mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 27: `logging.basicConfig('

**Comment by nieallen** [comment]
> thanks, I was trying to run data-gen.sh, the reported error is as follows:
> 
> /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 10: $'\nData pre-processing: build vocabularies and binarize training data.\n': command not found /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 12: import: command not found /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 13: import: command not found /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 14: import: command not found /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 15: import: command not found from: can't read /var/mail/collections from: can't read /var/mail/itertools from: can't read /var/mail/multiprocessing from: can't read /var/mail/fairseq /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 22: import: command not found from: can't read /var/mail/binarizer_fc from: can't read /var/mail/fairseq.data /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 27: syntax error near unexpected token `newline' /mnt/njh/FastCorrect/FC_utils/preprocess_fc.py: line 27: `logging.basicConfig('

there's another question: I do import fairseq.dataclass from the command line, the error is: ModuleNotFoundError: No module named 'fairseq.dataclass'
