### ISSUE TITLE
FastCorrect预训练模型不能下载

### ISSUE THREAD

**Issue by fh520** [microsoft/NeuralSpeech#113]
如题，https://msramllasc.blob.core.windows.net/modelrelease/fastcorrect_pretrain.pt
模型访问不了

**Comment by YichongLeng** [comment]
Sorry, we are facing some issues on internal storage. Please wait for a couple of days until the issue addressed. Thanks~

**Comment by YichongLeng** [comment]
I temporarily use the Google Drive to share the model. You can have a check.
