### ISSUE TITLE
cannot download softcorrect pretrained pt

### ISSUE THREAD

**Issue by vincentz0602** [microsoft/NeuralSpeech#114]
Hi, sorry to bother.
I can't download softcorrect pretrained model, it said Public access is not permitted.
It will be grateful if you can help.

**Comment by YichongLeng** [comment]
Sorry, we are facing some issues on internal storage. Please wait for a couple of days until the issue addressed. Thanks~

**Comment by YichongLeng** [comment]
I temporarily use the Google Drive to share the model. You can have a check.
