### ISSUE TITLE
The AISHELL-1 dataset for FastCorrect2 could not be downloaded？

### ISSUE THREAD

**Issue by zzz-cs** [microsoft/NeuralSpeech#115]
Hello, when I do this: The fine-tuning data of FastCorrect 2 on AISHELL-1 can be found in  [here](https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect2_training_data_aishell.tar.gz).
Error: This XML file does not appear to have any style information associated with it. The document tree is shown below. 
Could you please provide the AISHELL1 training data set of Fastcorrect2?

**Comment by YichongLeng** [comment]
Sorry, we are facing some issues on internal storage. Please wait for a couple of days until the issue addressed. Thanks~

**Comment by zzz-cs** [comment]
ok, thanks, SoftCorrect has a similar problem
