### ISSUE TITLE
cannot visit the model release page 

### ISSUE THREAD

**Issue by philipgao518** [microsoft/NeuralSpeech#116]
Hello, I cannot visit the model zoo page for couple of days. It said Public access is not permitted. Can u help?

**Comment by philipgao518** [comment]
if still need time to fix it, can u release the sentencepiece-model(https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect_zhwiki_sentencepiece.model) in any way?

**Comment by philipgao518** [comment]
if still need time to fix it, can u release the sentencepiece-model(https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect_zhwiki_sentencepiece.model) in any way first?

**Comment by YichongLeng** [comment]
I temporarily use the Google Drive to share the model. You can have a check.

**Comment by philipgao518** [comment]
> I temporarily use the Google Drive to share the model. You can have a check.

Thanks a lot, can download now!
