### ISSUE TITLE
[LightSpeech] trained model download issue

### ISSUE THREAD

**Issue by chengwuxinlin** [microsoft/NeuralSpeech#121]
Just wanted to say I really appreciate the cool stuff you've been working on! 😊 Tried to download the trained model checkpoint through the Google Drive link, but it came with an "Access Denied" message.

[7. Trained Checkpoint](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#7-trained-checkpoint)
We release our trained model checkpoint [here](https://drive.google.com/file/d/1ysGWcqos6DsMq0AmtdPIeU3IkVwziXa8/view?usp=sharing). You can donwnload it and place it under checkpoints/lightspeech. Then you can do the inference following [step 6](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#6-inference).

**Comment by YichongLeng** [comment]
Fixed! Let me know if the issue persists.

**Comment by chengwuxinlin** [comment]
Thanks for the fast response. However, I'm facing some TTS issues in LightSpeech too. 

`
[8. Inference with User Input](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#8-inference-with-user-input)
tasks/lightspeech_inference.py provides the text-to-speech inference of LightSpeech with user input text file defined by --inference_text. Refer to inference_text.txt for an example.

# the following command performs text-to-speech inference from inference_text.txt
export CUDA_VISIBLE_DEVICES=0
export PYTHONPATH=.
python tasks/lightspeech_inference.py \
    --config configs/tts/lj/lightspeech.yaml \
    --exp_name lightspeech \
    --reset \
    --inference_text inference_text.txt
Samples are saved to the folder checkpoints/[exp_name]/inference_[inference_text]_[step].
`

After I run this command, there is no wav file saved. In terminal, it says:

`10/13 07:52:19 PM model and trainer restored from checkpoint: checkpoints/lightspeech\model_ckpt_steps_100000.ckpt
Validation sanity check: 100%|████████████████████████████████████████████████████████| 5/5 [00:03<00:00,  2.17batch/s]
==============
 valid results: {'total_loss': 0.2584, 'mel': 0.2584, 'dur': 0.084, 'uv': 0.3188, 'f0': 0.9047}
==============

Epoch 1493:   0%| | 1/265 [00:00<02:11,  2.01batch/s, batch_size=35, dur=0.112, f0=0.597, loss_0=1.3, lr=0.000395, mel=
==============
 Epoch 1492 ended. Steps: 100000. {'total_loss': 1.3003, 'mel': 0.233, 'dur': 0.1118, 'uv': 0.3586, 'f0': 0.597, 'batch_size': 35.0}
==============

| Training end..
Epoch 1493:   0%| | 1/265 [00:00<02:14,  1.96batch/s, batch_size=35, dur=0.112, f0=0.597, loss_0=1.3, lr=0.000395, mel=`

Seems like it goes to the training step. Do I misunderstand the NO.8 indication? what is the correct step to perform TTS with the user's input?

**Comment by chengwuxinlin** [comment]
It works now, thanks!
