### ISSUE TITLE
eval_data/test no correction  WER=4.31% ?

### ISSUE THREAD

**Issue by xiaoxi91** [microsoft/NeuralSpeech#13]
你好,我发现论文里给出的aishell-1的test set 和dev set 在no correction下的性能分别为 4.31%和4.03%
但统计你们提供的eval_data文件夹下的data.json文件性能test/dev性能分别是4.83%和4.46%

**Comment by xiaoxi91** [comment]
那你们开源的aishell-v1训练集werdur_data_aishell是和最新公布的harder_eval_data使用的相同解码配置吗?还是和之前公布的eval_data是相同解码配置呢?

**Comment by xiaoxi91** [comment]
那你们开源的aishell-v1训练集werdur_data_aishell是和最新公布的harder_eval_data使用的相同解码配置吗?还是和之前公布的eval_data是相同解码配置呢?

**Comment by xiaoxi91** [comment]
> We mistakenly copy eval data of FastCorrect to FastCorrect 2. I upload the eval data in FastCorrect 2 in https://github.com/microsoft/NeuralSpeech/tree/master/FastCorrect2/eval_data/harder_eval_data.

那你们开源的aishell-v1训练集werdur_data_aishell是和最新公布的harder_eval_data使用的相同解码配置吗?还是和之前公布的eval_data是相同解码配置呢?

**Comment by YichongLeng** [comment]
The corresponding training data of harder eval data can be found in (https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect2_harder_training_data_aishell.tar.gz).
