### ISSUE TITLE
FastCorrect结果评估

### ISSUE THREAD

**Issue by exiaxu** [microsoft/NeuralSpeech#15]
作者你好，按照FastCorrect的Readme，最后一步评估效果的脚本执行后 提示“sclite: Error, Reference file 'path/to/ref.trn' does not exist“ ，请问是什么问题？

**Comment by YichongLeng** [comment]
Since the usage of cal_wer_aishell is "bash cal_wer_aishell.sh \<path-to-result\> \<path-to-sctk-bin\>", make sure that the result "data.json" from FastCorrect model is in \<path-to-result\> and \<path-to-sctk-bin\> should be something like "/home/xxx/sctk-2.4.10/bin".

**Comment by exiaxu** [comment]
> Since the usage of cal_wer_aishell is "bash cal_wer_aishell.sh <path-to-result> <path-to-sctk-bin>", make sure that the result "data.json" from FastCorrect model is in <path-to-result> and <path-to-sctk-bin> should be something like "/home/xxx/sctk-2.4.10/bin".

当前我的目录结构主要如下：
├── cal_wer_aishell.sh
├── eval_aishell.py
├── install_sctk.sh
├── LICENCE.TXT
├── save_dir/
│   ├── checkpoint28.pt
│   ├── log_aishell_e28/
│   ├── results_28_aishell_b0_t0.0/
│   └── tmp_28_aishell_b0_t0.0/
└── sctk-2.4.10/
    ├── bin/
    ├── doc/
    └── src/
执行评估脚本 bash cal_wer_aishell.sh ./save_dir/results_28_aishell_b0_t0.0/dev  ./sctk-2.4.10/bin  后仍是有这个问题
![image](https://user-images.githubusercontent.com/15244356/161237941-cf741460-886f-4a5d-9467-da1e69260d3e.png)

**Comment by exiaxu** [comment]
我看在评估脚本中是直接指定了这个文件，但是从train_ft.sh，以及test_ft.sh 的脚本中， 没有发现有关于 ref.trn 和 hyp.trn 的产出过程，这部分可以解惑一下吗？ 谢谢🙏

**Comment by YichongLeng** [comment]
The calculation of WER is borrowed from ESPNet (e.g. https://github.com/espnet/espnet/blob/master/egs/aishell/asr1/run.sh#L277). I think maybe you can refer to the code of ESPNet?

If the problem persists, maybe you can share the data.json to me and I can have a check when I am free tomorrow.

**Comment by exiaxu** [comment]
感谢回复，我仔细看了一下，这两个文件需要自己先定义个空的，然后脚本才会往里面进行写入，我已经解决了。你们的文章非常好，从中受益很多，再次感谢 👍

**Comment by dahu1** [comment]
请问楼主问题解决了吗？我使用你的方法，touch了空的hyp.trn 和 ref.trn ，没啥用啊。
<img width="884" alt="image" src="https://user-images.githubusercontent.com/22560013/163087043-6b44f13b-84b7-409b-a6bd-65e6323de86d.png">

**Comment by exiaxu** [comment]
> 请问楼主问题解决了吗？我使用你的方法，touch了空的hyp.trn 和 ref.trn ，没啥用啊。 <img alt="image" width="884" src="https://user-images.githubusercontent.com/22560013/163087043-6b44f13b-84b7-409b-a6bd-65e6323de86d.png">

如果这个不行，你可以按照 score_sclite.sh 脚本里的执行过程自己手动的跑一下，json2trn.py 这个脚本里会自己创建这两个文件，然后你再执行后面的看看。。

**Comment by dahu1** [comment]
> > 请问楼主问题解决了吗？我使用你的方法，touch 了空的 hyp.trn 和 ref.trn ，没啥用啊。 <img alt="image" width="884" src="https://user-images.githubusercontent.com/22560013/163087043-6b44f13b-84b7-409b-a6bd-65e6323de86d.png">
> 
> 如果这个不行，你可以按照 score_sclite.sh 脚本里的执行过程自己手动的跑一下，json2trn.py 这个脚本里会自己创建这两个文件，然后你再执行后面的看看。。

嗯嗯，看明白了，感谢回复

**Comment by wange12** [comment]
> > > 请问楼主问题解决了吗？我使用你的方法，touch 了空的 hyp.trn 和 ref.trn ，没啥用啊。 <img alt="image" width="884" src="https://user-images.githubusercontent.com/22560013/163087043-6b44f13b-84b7-409b-a6bd-65e6323de86d.png">
> > 
> > 
> > 如果这个不行，你可以按照 score_sclite.sh 脚本里的执行过程自己手动的跑一下，json2trn.py 这个脚本里会自己创建这两个文件，然后你再执行后面的看看。。
> 
> 嗯嗯，看明白了，感谢回复

你好请问你的问题解决了嘛 我同样结果都为0

**Comment by Futuresing** [comment]
> > > > 请问楼主问题解决了吗？我使用你的方法，touch 了空的 hyp.trn 和 ref.trn ，没啥用啊。 <img alt="image" width="884" src="https://user-images.githubusercontent.com/22560013/163087043-6b44f13b-84b7-409b-a6bd-65e6323de86d.png">
> > > 
> > > 
> > > 如果这个不行，你可以按照 score_sclite.sh 脚本里的执行过程自己手动的跑一下，json2trn.py 这个脚本里会自己创建这两个文件，然后你再执行后面的看看。。
> > 
> > 
> > 嗯嗯，看明白了，感谢回复
> 
> 你好请问你的问题解决了嘛 我同样结果都为0
先运行一下json2trn.py 这个脚本，再运行cal_wer_aishell.sh
