### ISSUE TITLE
LightSpeech: Code for inference?

### ISSUE THREAD

**Issue by agonzalezd** [microsoft/NeuralSpeech#17]
Greetings and first of all, thanks for your repository.

I have a question regarding the inference of LightSpeech. Since the aim of a TTS system is to provide a system that can take a text input and synthesise an audio, I find it rather difficult to achieve this purpose with this code. 

Is there any code for synthesising any text given as input? As an example, in [this](https://github.com/rishikksh20/FastSpeech2) repository of FastSpeech2, they provide a script for synthesis:

```bash
python .\inference.py -c .\configs\default.yaml -p .\checkpoints\first_1\ts_version2_fastspeech_fe9a2c7_7k_steps.pyt --out output --text "ModuleList can be indexed like a regular Python list but modules it contains are properly registered."
```

Thanks in advance.

**Comment by renqianluo** [comment]
Hi @agonzalezd , previously we did not support this feature. And we support this feature now. Please git pull the latest code and refer to the README.md [here](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#8-inference-with-user-input)
