### ISSUE TITLE
FastCorrect: some question of data preparation

### ISSUE THREAD

**Issue by YanghuiLi** [microsoft/NeuralSpeech#19]
Excuse me. Is werdur_data_aishell/dict.CN_char.txt extracted from the wiki data?

Is there any usage of the frequency of the tokens ?

**Comment by YichongLeng** [comment]
The frequency is not used. The dictionary is extracted from our internal corpus. Since Chinese character is limited, you can also extract a similar dictionary from wiki corpus.

**Comment by YanghuiLi** [comment]
Thanks.
Can I load sentencepiece directly from werdur_data_aishell/dict.CN_char.txt? I want to tokenize my data based on dict.CN_char.txt, but it seems loading sentencepiece requires *.model.

**Comment by YichongLeng** [comment]
No. Indeed, for Chinese character, you can perform tokenization just by inserting space, e.g., "token = ' '.join(text)".
