### ISSUE TITLE
so many bugs

### ISSUE THREAD

**Issue by jinfagang** [microsoft/NeuralSpeech#2]
LightSpeech/tasks/lightspeech.py", line 568, in save_result
    audio.save_wav(wav_out, f'{gen_dir}/wavs/{base_fn}.wav', hparams['audio_sample_rate'],
KeyError: 'audio_sample_rate'
"""

**Comment by renqianluo** [comment]
Hi @jinfagang , seems the same as https://github.com/microsoft/NeuralSpeech/issues/3#issuecomment-1076150732
