### ISSUE TITLE
adapterASR中部分函数缺乏定义

### ISSUE THREAD

**Issue by WZLHQ** [microsoft/NeuralSpeech#20]
首先感谢开源

但是遇到一些问题：
e2e_asr_adaptertransformer.py中to_device\to_torch_tensor\pad_list等一些函数缺乏定义就使用了。可以提供一个完整无错的版本吗？

期待您的回复

**Comment by houwenxin** [comment]
感谢你使用我们的代码并提出的问题，已改正，请参考这个commit：93910eb8375c6e074d3356c9ae72715356323aa7
