### ISSUE TITLE
"E2E" object has no attribute error

### ISSUE THREAD

**Issue by WZLHQ** [microsoft/NeuralSpeech#22]
你好
关于上个issue中，我已经加上from espnet.nets.pytorch_backend.nets_utils import *，但是加上后又报错了，比如：
"E2E" object has no attribute "logzero"
"E2E" object has no attribute "_get_last_yesq"等
我尝试在E2E的父类中寻找相关的属性，但是没有找到
请问这仍是缺少了相关的定义吗？
期待您的回复

**Comment by WZLHQ** [comment]
我并没有安装easyespnet，我使用的是espnet0.10.6这个版本，是因为这二者有什么不同所以才造成这种报错吗？请指点

**Comment by WZLHQ** [comment]
我跑的是adapter_example；
环境为：Ubuntu1804+python37+torch181+GTX TITAN X+espnet0.10.6

**Comment by houwenxin** [comment]
你好，因为我们自己实现了batch beam search，所以请安装使用这个版本的espnet：https://github.com/houwenxin/espnet/tree/batch-decoding
