### ISSUE TITLE
Fastcorrect2: Could you upload your pre-processed wiki pre-trained data and your pre-trained log?

### ISSUE THREAD

**Issue by Amber921463001** [microsoft/NeuralSpeech#23]
I want to Reproduce the results of the paper Fastcorrect2. Could you please upload your pre-processed wiki pre-trained data and your pre-trained log ？

**Comment by YichongLeng** [comment]
We pre-train FastCorrect 2 on our internal data rather then wiki data. Wiki data is just an example of unpair text data. You can collect and pre-process the unpair text data and pretrain the model by yourself.

**Comment by YichongLeng** [comment]
Our corpus have 400M sentences and pre-training 10 epochs is enough to achieve good results.

**Comment by Amber921463001** [comment]
ok，Thank you!
