### ISSUE TITLE
Question about Fastcorrect2

### ISSUE THREAD

**Issue by ZhangChun96** [microsoft/NeuralSpeech#24]
Hello, I am running Fastcorrect2. But I have some questions about the test set in the eval_data folder: in the data.json, for a uttid ,   there are 4 candidate paths in the 'rec_text'  . I would like to wonder , the wer of  test set mentioned in the paper is 4.31%, does it have any relationship with the  'rec_text'？ Thanks a lot !

**Comment by YichongLeng** [comment]
The first candidate is used for the calculation of WER of ASR model (i.e., 4.83% for eval_data/test and 4.31% for eval_data/harder_eval_data/test).
