### ISSUE TITLE
LightSpeech fine-tuning

### ISSUE THREAD

**Issue by texpomru13** [microsoft/NeuralSpeech#25]
Could you tell me if it is possible to fine-tune the model? If yes, what steps do I need to take to do this?

**Comment by renqianluo** [comment]
@texpomru13  It is possible to fine-tune the model, though I do not try it. You can place the trained checkpoint (e.g., our trained checkpoint) under the corresponding path (e.g., [Step 7 in README](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#7-trained-checkpoint)) and the program will automatically reload that model.
```bash
mkdir -p checkpoints/lightspeech
cd checkpoints/lightspeech
wget https://msramllasc.blob.core.windows.net/modelrelease/LightSpeech/model_ckpt_steps_100000.ckpt
cd ../../
export CUDA_VISIBLE_DEVICES=0,1,2,3 #may change this to the appropriate number on your machine
export PYTHONPATH=.
### continue training
### remember to edit the lightspeech.yaml file to modify the parameters ( e.g., training steps, your data path, learning rate ... ) or pass them via --hparams
python tasks/lightspeech.py \
    --config configs/tts/lj/lightspeech.yaml \
    --exp_name lightspeech \
    --reset
```
