### ISSUE TITLE
FastCorrect: finetuned paired data overlapped with ASR model training data?

### ISSUE THREAD

**Issue by tbright17** [microsoft/NeuralSpeech#29]
Hi,

Thanks for sharing the code. Based on the paper, it looks like you train the ASR models on aishell-1 and internal dataset, and then use the trained models to transcribe the training data again to get finetuning data for FastCorrect. I think this could bring mismatch because the real hypothesis we want to correct is never seen during ASR model training.

Any thoughts?

Thanks

**Comment by YichongLeng** [comment]
FastCorrect learns the pattern where ASR model may make mistakes. As your points, the error pattern could be difference between the seen training data and the unseen test data.

Maybe we can separate the training data to two part and train two ASR models. For each model, one part is used for training and the other is used for transcribing. I think the mismatch issue probably exists but I am not sure whether or how much this simple solution will address this issue.

**Comment by tbright17** [comment]
> FastCorrect learns the pattern where ASR model may make mistakes. As your points, the error pattern could be difference between the seen training data and the unseen test data.
> 
> Maybe we can separate the training data to two part and train two ASR models. For each model, one part is used for training and the other is used for transcribing. I think the mismatch issue probably exists but I am not sure whether or how much this simple solution will address this issue.

Thanks for the reply. Will see if this makes any difference in my experiments.
