### ISSUE TITLE
NeuralSpeech/LightSpeech/tasks/lightspeech.py", line 572, in save_result     norm=hparams['out_wav_norm']) KeyError: 'out_wav_norm' """

### ISSUE THREAD

**Issue by jinfagang** [microsoft/NeuralSpeech#3]
NeuralSpeech/LightSpeech/tasks/lightspeech.py", line 572, in save_result
    norm=hparams['out_wav_norm'])
KeyError: 'out_wav_norm'
"""

Please make sure these params are mentioned in README before open source....

it make users very confused, since the code can not be RUN.

**Comment by renqianluo** [comment]
Hi @jinfagang , I do not have the same problem as yours. All the params are specified in the config files. How do you execute the code? Maybe you are not in the correct directory/path when you run the command so the config file can not be found ?

**Comment by jinfagang** [comment]
@renqianluo Hi. I just runing it by:

```
python -m tasks.lightspeech --config configs/tts/lj/lightspeech.yaml --exp_name lightspeech --infer

```

Nothing changed, just using CPU for inference (I manually solve it to CPU since original code doesn't support, also I don't konw how u tested time on CPU in your paper). It **can not be run without any modification**.

**Comment by jinfagang** [comment]
@renqianluo Hi, can u give a hand to verify this issue?

**Comment by renqianluo** [comment]
> @renqianluo Hi. I just runing it by:
> 
> ```
> python -m tasks.lightspeech --config configs/tts/lj/lightspeech.yaml --exp_name lightspeech --infer
> ```
> 
> Nothing changed, just using CPU for inference (I manually solve it to CPU since original code doesn't support, also I don't konw how u tested time on CPU in your paper). It **can not be run without any modification**.

@jinfagang Hi, to run on CPU, just set `CUDA_VISIBLE_DEVICES=`, without modifying the code. We have updated the README file on how to measure inference time (on GPU and CPU).  Please check the newest commit.

**Comment by renqianluo** [comment]
> @renqianluo Hi, can u give a hand to verify this issue? the params I printed out actually contains this field, but not accessable when save the wavs.

I cannot reproduce this error from my side. Do you execute the command in the correct path (`cd Neuralspeech/Lightspeech`)? Try the newest commit, with more detailed information in README.

**Comment by jinfagang** [comment]
@renqianluo yes. 

How can I inference on a single sentence, without loading eval dataset and actually just do evaluation? I want inference on a single sentence that doesn't presents in the dataset.

**Comment by jinfagang** [comment]
@renqianluo thank u! that would be great if we have this feature.

**Comment by renqianluo** [comment]
@jinfagang Hi, we have supported the feature of user input now. Please git pull the latest code and refer to [here](https://github.com/microsoft/NeuralSpeech/tree/master/LightSpeech#8-inference-with-user-input).

**Comment by jinfagang** [comment]
@renqianluo thanks for notice, will try it later!
