### ISSUE TITLE
what's the version number did you use in FastCorrection?

### ISSUE THREAD

**Issue by Chriszhangmw** [microsoft/NeuralSpeech#30]
Error:
ModuleNotFoundError: No module named 'fairseq.dataclass.data_class'

code:
from fairseq.dataclass.data_class import (
    CheckpointParams,
    CommonEvalParams,
    CommonParams,
    DatasetParams,
    DistributedTrainingParams,
    EvalLMParams,
    OptimizationParams,
)

**Comment by Chriszhangmw** [comment]
rename

**Comment by YichongLeng** [comment]
As mentioned in README, we use fairseq==0.10.1.
