### ISSUE TITLE
关于chinese_char_sim.txt和sim_prun_char.txt

### ISSUE THREAD

**Issue by zhengzheng-yay** [microsoft/NeuralSpeech#31]
非常感谢开源代码，我想问一下，在构造伪校正文本时，所使用的同音字词典是怎样制作的？

**Comment by YichongLeng** [comment]
The  homophone dictionary can be easily created by the following steps.

First, we can collect text data (e.g., from Wikipedia) and get a vocabulary.

Second, we can obtain the pronunciation (i.e., the phoneme sequence) of every word in the vocabulary by open-source grapheme-to-phoneme tools (e.g., [g2pM]( https://github.com/kakaobrain/g2pM) package for Mandarin or [g2p]( https://github.com/Kyubyong/g2p) package for English).

Third, we can calculate the similarity between the phoneme sequences of any two words in the vocabulary. Two words with a similarity higher than threshold are regarded as homophones. In our implementation, the similarity is the negative of ratio of edit distance of two phoneme sequences and average length of two phoneme sequences.

**Comment by tbright17** [comment]
> 

For Mandarin, we also need to consider tones. It's probably not optimal to treat toned finals in Mandarin as a single token when calculating edit distance, e.g. (sim(ao1, ao2) should be bigger than sim(ao1, ou1)).

**Comment by YichongLeng** [comment]
> > 
> 
> For Mandarin, we also need to consider tones. It's probably not optimal to treat toned finals in Mandarin as a single token when calculating edit distance, e.g. (sim(ao1, ao2) should be bigger than sim(ao1, ou1)).

Yes, I think tones will help the model.

**Comment by ycchuang** [comment]
What is the different between chinese_char_sim.txt and sim_prun_char.txt in add_noise.py? 
Are they represent different similarity as "the negative of ratio of edit distance of two phoneme sequences" and "average length of two phoneme sequences". 
chinese_char_sim.txt seems related to same phoneme with diffenent tones, but how to create the sim_prun_char.txt?
