### ISSUE TITLE
What is demo "TBD"

### ISSUE THREAD

**Issue by thongvhoang** [microsoft/NeuralSpeech#32]
Hi. My name is Thong Vo. 
Tell me what is 'TBD' in demo. 
Thank you.
![Screenshot from 2022-05-04 14-21-07](https://user-images.githubusercontent.com/42695481/166637908-bce84c32-d6e7-4682-911a-3d00f0034a0e.png)

**Comment by sonovice** [comment]
"To be done" - it's apparently not yet finished.

**Comment by thongvhoang** [comment]
> "To be done" - it's apparently not yet finished.
Yes. It's done.
