### ISSUE TITLE
Can not load FastCorrect pretrain model

### ISSUE THREAD

**Issue by qinyuenlp** [microsoft/NeuralSpeech#34]
Hi, 
I load your FastCorrect pretrain model by
```
from fastcorrect_model import FastCorrectModel
model = FastCorrectModel.from_pretrained('FastCorrect', checkpoint_file='fastcorrect_pretrain.pt')
```

then I get
```
RuntimeError: Error(s) in loading state_dict for NATransformerModel:
	Missing key(s) in state_dict: "decoder.embed_length.weight".
```

How can I load fastcorrect model correct?
Thanks.

**Comment by YichongLeng** [comment]
Try [this](https://github.com/microsoft/NeuralSpeech/blob/master/FastCorrect/eval_aishell.py#L16).

**Comment by YingjiaoLiu** [comment]
> I solve it by modifying `arch` in pretrain model file
> 
> ```python
> weight = torch.load('fastcorrect_pretrain.pt')
> weight["args"].arch="fastcorrect"
> ```

I met the same problem. could you please specify which file or which part of the code to modify like this? Many thanks!!!
