### ISSUE TITLE
fastcorrect2：What was the format of the data before running align_cal_werdur_v2.py?

### ISSUE THREAD

**Issue by Amber921463001** [microsoft/NeuralSpeech#35]
What was the format of the data before running align_cal_werdur_v2.py?

**Comment by Amber921463001** [comment]
If there is only one outcome of ASR data, how should training data be constructed? Thank you！

**Comment by YichongLeng** [comment]
For the source file, it will be (tokenized) nbest candidates joined by " # ". For the target file, it will be the (tokenized) target.

**Comment by wangnanna** [comment]
The align_cal_werdur_v2.py needs two input files, can you give some example pictures or specific two corresponding data examples for these two files? This can really help us better understand the required input form, Thank you very much！

**Comment by YichongLeng** [comment]
For the first (source) files, it can be (tokenized nbest candidates joined by " # "):

I love hat # I love cat # I love bat

For the second (target) files, it can be (tokenized target):

I love cat

**Comment by YichongLeng** [comment]
> If there is only one outcome of ASR data, how should training data be constructed? Thank you！

If there is no beam search results from ASR, I think you should use FastCorrect instead of FastCorrect2.
