### ISSUE TITLE
FastCorrect: pseudo data pre-processing

### ISSUE THREAD

**Issue by jasonzzj97** [microsoft/NeuralSpeech#36]
Hi,

Thanks for the repo!
I followed the FastCorrect Step 1 in README and extracted wiki text for pseudo dataset generation. From your instructions:

> Also, we can perform some further pre-processing such as 1) removing non-Chinese letter, 2) splitting sentence, 3) changing number to its corresponding Chinese letter.

Are these further pre-processing steps necessary before we use `scripts/align_cal_werdur_v2.py` to align the sentences? Or are these steps included in any scripts in this repository?

Thank you!

**Comment by YichongLeng** [comment]
We use an internal tools for pre-processing, which is not included in repo.

Except the steps mentioned in README, I think there is no further pre-processing steps necessary (maybe you can have a look on wiki data and check whether there are some dataset-specific pre-processing that are needed).

**Comment by jasonzzj97** [comment]
Hi,
I see. Thank you for the information!

**Comment by AlanYen** [comment]
我正尝试使用 FastCorrect (v1) 来作一些实验,
想请问作预训练时,产生的伪数据集,
正确句子(跟 Reference 相同)跟故意弄错的句子(跟 Reference 有所不同)的数量比例是否有影响,有建议的比例吗?
