### ISSUE TITLE
fastcorrect2的训练数据的格式是什么？

### ISSUE THREAD

**Issue by Amber921463001** [microsoft/NeuralSpeech#4]
请问fastcorrect2的训练数据的格式是什么？

**Comment by YichongLeng** [comment]
The fine-tuning data of FastCorrect 2 on AISHELL-1 can be found in (https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect2_training_data_aishell.tar.gz). You can find the format in this data.

**Comment by Amber921463001** [comment]
Thank you for your reply！I have another question. How to load pretrained model? I didn‘t find the restore-file.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月23日(星期三) 晚上6:55
收件人: ***@***.***&gt;; 
抄送: "ivy ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/NeuralSpeech] fastcorrect2的训练数据的格式是什么？ (Issue #4)





 
The fine-tuning data of FastCorrect 2 on AISHELL-1 can be found in (https://msramllasc.blob.core.windows.net/modelrelease/FastCorrect2_training_data_aishell.tar.gz). You can find the format in this data.
