### ISSUE TITLE
FastCorrect中的eval_data怎么生成的？

### ISSUE THREAD

**Issue by whz-NJ** [microsoft/NeuralSpeech#44]
FastCorrect中的eval_data怎么生成的？我想构造自己的验证数据应该怎么构造啊？

**Comment by whz-NJ** [comment]
参照eval_data中的data.json写代码构造

**Comment by YingjiaoLiu** [comment]
> 参照eval_data中的data.json写代码构造

请问data.json里面的score是怎么计算的？这个score影响推理和效果统计吗
