### ISSUE TITLE
why you fix a package that not released yet to requirements??

### ISSUE THREAD

**Issue by jinfagang** [microsoft/NeuralSpeech#5]
I just want save other users time, your code have too many bugs. I can't tolerant about it.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/21303438/159694276-982b6932-11fd-4a68-b17c-75ac5f6203ff.png">

pytorch_lightning 1.6.0 does NOT released yet. the latest version is 1.5.0

ALSO, even you installed from GitHub source code , the APIs are not going like your codes:

```
# from pytorch_lightning.callbacks.pt_callbacks import ModelCheckpoint
from pytorch_lightning.callbacks.model_checkpoint import ModelCheckpoint
```

there is no such `from pytorch_lightning.callbacks.pt_callbacks` in latest pytorch_lightining code.

Again, please fix your code bugs before release!!!

**Comment by renqianluo** [comment]
The initial release was pytorch_lightning==0.6.0. It was incorrectly changed to 1.6.0, and we soon fixed it. Please see the newer commit.
