### ISSUE TITLE
No module named 'fastcorrect_generator'

### ISSUE THREAD

**Issue by HuangJian-whu** [microsoft/NeuralSpeech#6]
FastCorrect/fastcorrect_model.py
   from fastcorrect_generator import DecoderOut

How or where to install fastcorrect_generator?

**Comment by YichongLeng** [comment]
Try to add "FC_utils" folder to PYTHONPATH like:
export PYTHONPATH=<PATH-to-FastCorrect>/FC_utils:$PYTHONPATH
