### ISSUE TITLE
can't  find gram2.txt/gram3.txt file

### ISSUE THREAD

**Issue by spxia** [microsoft/NeuralSpeech#7]
./scripts/align_cal_werdur_v2.py
Traceback (most recent call last):
  File "./scripts/align_cal_werdur_v2.py", line 257, in <module>
    print("Loading gram2:", gram2_path)
NameError: name 'gram2_path' is not defined

How to make it？Or can you provide it?

**Comment by YichongLeng** [comment]
Sorry for not commenting out this code. The description of ngram file is as follows and has been updated to code.

The format of gramx.txt is \<space-split ngram token\> \t frequency
such as: 
good morning\t1000\n
the gramx.txt can be calculated based on unpaired text data.
