### ISSUE TITLE
fairseq-train: error: the following arguments are required: data

### ISSUE THREAD

**Issue by Amber921463001** [microsoft/NeuralSpeech#8]
运行train_ft.sh的时候报错：fairseq-train: error: the following arguments are required: data
我已经在train_ft.sh里设置了DATA_PATH=  '/XXX/FastCorrect/data/werdur_data_aishell'
请问这个报错该如何解决？

**Comment by Amber921463001** [comment]
已经事先用data-gen.sh处理了训练数据，并把处理结果放进data/werdur_data_aishell里

**Comment by YichongLeng** [comment]
I can only reproduce your error in the condition when I set DATA_PATH to an empty variable.

Note that in Shell the space can cause empty variable, i.e., “DATA_PATH=xxx” is right while "DATA_PATH= xxx" will cause an empty variable.

**Comment by banbsyip** [comment]
> 已经事先用data-gen.sh处理了训练数据，并把处理结果放进data/werdur_data_aishell里

我连data-gen.sh都没运行成功，总是FC_utils/preprocess_fc.py: Syntax error: newline unexpected (expecting ")")报错，不知道为什么
