### ISSUE TITLE
FastCorrect2: Prepare pseudo paired dataset is too slow

### ISSUE THREAD

**Issue by Arrivederci** [microsoft/NeuralSpeech#9]
I tried to pretrain a FastCorrect2 model with 200M unpaired data. I used **align_cal_werdur_v2.py** to align noised text pairs.  Looks it can only align 100 pairs/s even I created 40 processes... Could you give me some idea to speed it up or just release a pretrained model?

**Comment by YichongLeng** [comment]
Yes. We will update a faster version of alignment script in the next one or two days.

**Comment by Arrivederci** [comment]
> Yes. We will update a faster version of alignment script in the next one or two days.

Thanks

**Comment by YichongLeng** [comment]
I have updated a faster version of alignment in (https://github.com/microsoft/NeuralSpeech/tree/master/FastCorrect2/scripts/align_cal_werdur_fast.py), which can align more than 100 pairs/s on a single CPU.

Feel free to let me know if there is any problem about using this script.

**Comment by Arrivederci** [comment]
@YichongLeng 
Great! The new script is 30x faster than the previous on my work. Looks like I won't have to spend a month preparing my dataset, Thanks. Btw, does the new script get the same result as before?

**Comment by YichongLeng** [comment]
Yes, we perform an experiment on our internal dataset and the performance drop of fast alignment is very very slightly.
