### ISSUE TITLE
SoftCorrect ,Test the error corrector,When I execute the script "runs/test_corrector.sh" ,Errors encountered

### ISSUE THREAD

**Issue by zhangkg2016** [microsoft/NeuralSpeech#90]
data.json content such as 
![微信截图_1](https://user-images.githubusercontent.com/12874343/231378698-6c73b45e-c4da-49d5-a3db-623bb51118be.png)

When I execute the script `runs/test_corrector.sh`，eval_corrector.py has error like this 
![微信截图_20230412150902](https://user-images.githubusercontent.com/12874343/231379261-51d5c159-f834-4fca-8c80-6c013e447416.png)

**The variable content is：**
```
rec_token_score = [-3.7221150398254395, -14.028525352478027, -14.243535995483398, -14.27415657043457]

text = '广 州 市 房 地 产 中 介 协 会 分 析  #  广 州 市 房 地 产 中 介 协 会 分 系  #  广 州 市 房 地 产 中 介 协 会 分 许  #  广 州 市 房 地 产 中 介 协 会 分 享'

```
I'm trying to change the code to： `assert len(rec_token_score) == len(text.split('#'))`, A new error has occurred：

![微信截图_20230412151607](https://user-images.githubusercontent.com/12874343/231381177-23b1bb6a-55c8-4621-83ad-34e8a91bc6cb.png)

**The variable content is**：
```
src_item = tensor([  1, 409, 485, 150, 321,  67, 187,  28, 746, 827,  24,  77, 847,   3,
        409, 485, 150, 321,  67, 187,  28, 746, 827,  24,  77, 210,   3, 409,
        485, 150, 321,  67, 187,  28, 746, 827,  24,  77, 476,   3, 409, 485,
        150, 321,  67, 187,  28, 746, 827,  24,  77, 753,   2])

self.force_mask_type = [0, 0, 4, 4, 4, 0]

```

**Can you help me solve my question？Thanks!**

**Comment by zhangkg2016** [comment]
已解决

**Comment by paopaoyaya** [comment]
Have you solved this problem, and how? Thank you！
